
// const TEXT_CONSTANT = {
//     EXPRESS :"frenchExpenses",
//     ORDER:"frenchOrders",
//     FUNDS_INOUT:"frenchFunds in and out",
//     ADJUSTMENT:"frenchAdjustment",
//     PURCHASE:"frenchPurchase",
//     REVERSE:"frenchRefunds, claims, disputes",
//     REPAYMENT:"frenchLoan payments",
//     TAX:"frenchTaxes",
// }


export const TEXT_CONSTANT = {
    EXPENSE:"Expenses",
    FEES:"eBay fees",
    TRANSACTION_FEES:"Transaction fees",
    PROMOTED_LISTING_FEES:"Promoted listing fees",
    INSERTION_FEES:"Insertion fees",
    ADVANCED_LISTING_UPGRADE_FEES:"Advanced listing upgrade fees",
    OTHER_FEES:"Other ebay fees",
    SHIPPING_LABEL:"Shipping label",
    ORDER:"Orders",
    FUNDS_INOUT:"Funds in and out",
    PAYOUT:"Payout",
    TRANSFER:"Transfer",
    ADJUSTMENT:"Adjustment",
    PURCHASE:"Purchase",
    REVERSE:"Refunds, claims, disputes",
    REFUND:"Gross refund",
    CLAIM:"Gross claim",
    PAYMENT_DISPUTE:"Gross payment dispute",
    REPAYMENT:"Loan payments",
    TAX:"Taxes",
    ACCOUNT_SUMMARY:"Account Summary",
    TRANSACTIONS_SUMMARY:"Transactions Summary",
    DEBITS:"Debits",
    CREDITES:"Credits",
    NET:"Net",
    SUB_TOTAL:"Subtotal",
    REPORT_NUMBER:"Report number",
    PAYMENT_ACTIVITY_REPORT:"Payment activity report",
    DATE_RANGE:"Date range",
    GENERATED:"Generated",
    VIEW_REPORT_EXAMPLE:"View example report",
    PAYMENT_EXAMPLE_REPORT:"Payment activity example report",
    DOWNLOAD_PDF:"Download PDF",
}

export const AMOUNT_TYPE = ["DEBITS","CREDITES","NET"]
